学科:
    - Artificial Intelligence
    - Civil Engineering
置顶: true
窗口宽度: 600
窗口高度: 900
复制后延迟（秒）: 0.2
代理端口: 127.0.0.1:7890

GLM:
  key: key
  model: glm-4-air
  url: https://open.bigmodel.cn/api/paas/v4/
deepseek:
  key: key
  model: deepseek-chat
  url: https://api.deepseek.com
阿里: 
  key: key
  model: qwen-long
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
讯飞:
  key: key
  model: 4.0Ultra
  url: https://spark-api-open.xf-yun.com/v1
字节:
  key: key
  model: endpoint_id
  url: https://ark.cn-beijing.volces.com/api/v3
腾讯:
  key: key
  model: hunyuan-standard-256K
  url: https://api.hunyuan.cloud.tencent.com/v1
本地:
  key: key
  model: model
  url: http://localhost:8080/v1
